INSERT INTO BOOKS (TITLE, AUTHOR, PRICE, CATEGORY, ACTIVE, CREATED_AT, UPDATED_AT, DELETED_AT) VALUES ('The Great Gatsby', 'F. Scott Fitzgerald', 7.99, 'Fiction', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO BOOKS (TITLE, AUTHOR, PRICE, CATEGORY, ACTIVE, CREATED_AT, UPDATED_AT, DELETED_AT) VALUES ('The Da Vinci Code', 'Dan Brown', 9.99, 'Mystery', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO BOOKS (TITLE, AUTHOR, PRICE, CATEGORY, ACTIVE, CREATED_AT, UPDATED_AT, DELETED_AT) VALUES ('The Hobbit', 'J.R.R. Tolkien', 12.99, 'Fantasy', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO BOOKS (TITLE, AUTHOR, PRICE, CATEGORY, ACTIVE, CREATED_AT, UPDATED_AT, DELETED_AT) VALUES ('1984', 'George Orwell', 6.99, 'Fiction', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO BOOKS (TITLE, AUTHOR, PRICE, CATEGORY, ACTIVE, CREATED_AT, UPDATED_AT, DELETED_AT) VALUES ('The Catcher in the Rye', 'J.D. Salinger', 5.99, 'Fiction', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO BOOKS (TITLE, AUTHOR, PRICE, CATEGORY, ACTIVE, CREATED_AT, UPDATED_AT, DELETED_AT) VALUES ('The Hunger Games', 'Suzanne Collins', 8.99, 'Science Fiction', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO BOOKS (TITLE, AUTHOR, PRICE, CATEGORY, ACTIVE, CREATED_AT, UPDATED_AT, DELETED_AT) VALUES ('Lord of the Flies', 'William Golding', 6.99, 'Fiction', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO BOOKS (TITLE, AUTHOR, PRICE, CATEGORY, ACTIVE, CREATED_AT, UPDATED_AT, DELETED_AT) VALUES ('The Lord of the Rings', 'J.R.R. Tolkien', 14.99, 'Fantasy', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO BOOKS (TITLE, AUTHOR, PRICE, CATEGORY, ACTIVE, CREATED_AT, UPDATED_AT, DELETED_AT) VALUES ('Java for Dummies', 'Barry Burd', 19.99, 'Programming', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO BOOKS (TITLE, AUTHOR, PRICE, CATEGORY, ACTIVE, CREATED_AT, UPDATED_AT, DELETED_AT) VALUES ('Python for Dummies', 'Stef Maruch', 21.99, 'Programming', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO BOOKS (TITLE, AUTHOR, PRICE, CATEGORY, ACTIVE, CREATED_AT, UPDATED_AT, DELETED_AT) VALUES ('HTML & CSS: Design and Build Websites', 'Jon Duckett', 19.99, 'Programming', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO BOOKS (TITLE, AUTHOR, PRICE, CATEGORY, ACTIVE, CREATED_AT, UPDATED_AT, DELETED_AT) VALUES ('JavaScript and JQuery: Interactive Front-End Web Development', 'Jon Duckett', 21.99, 'Programming', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO BOOKS (TITLE, AUTHOR, PRICE, CATEGORY, ACTIVE, CREATED_AT, UPDATED_AT, DELETED_AT) VALUES ('Learning React: A Hands-On Guide to Building Web Applications Using React and Redux', 'Kirupa Chinnathambi', 29.99, 'Programming', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO BOOKS (TITLE, AUTHOR, PRICE, CATEGORY, ACTIVE, CREATED_AT, UPDATED_AT, DELETED_AT) VALUES ('Spring in Action', 'Craig Walls', 29.99, 'Programming', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO BOOKS (TITLE, AUTHOR, PRICE, CATEGORY, ACTIVE, CREATED_AT, UPDATED_AT, DELETED_AT) VALUES ('Spring Boot in Action', 'Craig Walls', 29.99, 'Programming', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO BOOKS (TITLE, AUTHOR, PRICE, CATEGORY, ACTIVE, CREATED_AT, UPDATED_AT, DELETED_AT) VALUES ('Spring Microservices in Action', 'John Carnell', 29.99, 'Programming', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO BOOKS (TITLE, AUTHOR, PRICE, CATEGORY, ACTIVE, CREATED_AT, UPDATED_AT, DELETED_AT) VALUES ('Spring Security in Action', 'Laurentiu Spilca', 29.99, 'Programming', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO BOOKS (TITLE, AUTHOR, PRICE, CATEGORY, ACTIVE, CREATED_AT, UPDATED_AT, DELETED_AT) VALUES ('Spring Web Flow 2 Web Development', 'Sven Lüppken', 29.99, 'Programming', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO BOOKS (TITLE, AUTHOR, PRICE, CATEGORY, ACTIVE, CREATED_AT, UPDATED_AT, DELETED_AT) VALUES ('Spring Web Services 2 Cookbook', 'Hamidreza Sattari', 29.99, 'Programming', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO BOOKS (TITLE, AUTHOR, PRICE, CATEGORY, ACTIVE, CREATED_AT, UPDATED_AT, DELETED_AT) VALUES ('Spring: Developing Java Applications for the Enterprise', 'Ravi Kant Soni', 29.99, 'Programming', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);



